package com.tyganeutronics.myratecalculator.auth

import android.app.Activity
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.tyganeutronics.myratecalculator.R

/**
 * Fetches a Google ID token for [AuthManager.linkGoogle].
 *
 * Credential Manager rather than GoogleSignInClient, which is deprecated. The account picker is
 * drawn by the system over the calling activity, so this needs a real Activity and not an
 * application context.
 *
 * Nothing here works until a SHA-1 fingerprint for the signing key is registered against the
 * Android app in the Firebase console — including the Play App Signing key, which is not the
 * one a local build uses. Without it the request fails with no usable credential.
 */
object GoogleCredential {

    private const val TAG = "GoogleCredential"

    sealed interface Result {
        data class Token(val idToken: String) : Result

        /** Backed out of the picker. An ordinary thing to do, and not worth a message. */
        data object Cancelled : Result

        /**
         * Everything else — and it must be reported. The most common cause is no SHA-1
         * fingerprint registered for this package in the Firebase console, which fails
         * *after* the account picker has already appeared and been used. Swallowing that
         * silently returns the user to the sign-in sheet with no idea what went wrong.
         */
        data object Failed : Result
    }

    suspend fun requestIdToken(activity: Activity): Result {
        // Generated by the google-services plugin from the web OAuth client in
        // google-services.json. The *web* client id is correct here, not an Android one.
        val serverClientId = activity.getString(R.string.default_web_client_id)

        val option = GetSignInWithGoogleOption.Builder(serverClientId).build()
        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()

        return try {
            val response = CredentialManager.create(activity).getCredential(activity, request)
            val credential = response.credential

            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                Result.Token(GoogleIdTokenCredential.createFrom(credential.data).idToken)
            } else {
                Log.w(TAG, "Unexpected credential type ${credential.type}")
                Result.Failed
            }
        } catch (e: GetCredentialCancellationException) {
            Result.Cancelled
        } catch (e: GetCredentialException) {
            Log.w(TAG, "Google credential request failed", e)
            Result.Failed
        }
    }
}
